theme: jekyll-theme-midnight

remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: EpsilonsQc GitHub Pages
description: A work in progress GitHub Pages.

show_downloads: false #indicate whether or not to provide a download URL
google_analytics: #[Your Google Analytics tracking ID]
